[注册信息]
machinecode = c90868656cc2b813
#=============注册码填写位置=============
userid = 5B1B2P0M3F2Q7K2L

[set]
#=============你的游戏路径=============
path = E:\梦幻西游时空\My\MyPCLauncher_x64r.exe
#=============窗口大小不要改。如果需要其它大小联系定制=============
width = 876
height = 684
全局延时 = 2
#=============多开数量，一般5开，太少没意义=============
windows = 5
#=============窗口左上角坐标。这是5个窗口叠起来的=============
窗口起始坐标 = 0, 0|0, 0|0, 0|0, 0|0, 0
#=============你要登录的服务器以及角色名，队长放第一个=============
服务器 = 缘来是你
角色 = 角色1,角色2,角色3,角色4,角色5
奶妈 = 2
#================多组服务器与角色配置（task_state.json也改为task_state1.json、task_state2.json的形式）================
共几组号 = 3
服务器1 = 2026
角色1 = 角色1,角色2,角色3,角色4,角色5
窗口起始坐标1 = 0, 0|0, 0|0, 0|0, 0|0, 0
奶妈1 = 0
服务器2 = 缘来是你
角色2 = 角色1,角色2,角色3,角色4,角色5
窗口起始坐标2 = 0, 0|0, 0|0, 0|0, 0|0, 0
奶妈 = 2
服务器3 = 天下无双
角色3 = 角色1,角色2,角色3,角色4,角色5
窗口起始坐标3 = 0, 0|0, 0|0, 0|0, 0|0, 0 
奶妈3 = 0
#=============多个帐号的设置在这里=============
#==全是手机号的也填邮箱，不过帐号要写成138****1111的形式==

#=========如果一组号里是多种帐号那么填混合=========
#========沙盒登录有可能记不住密码，也填混合=========
多账号 = False
账号类型 = 邮箱
账号 = 111111@163.com,123456|222222@163.com,123456|333333@163.com,123456|4444444@163.com,123456|5555555@163.com,123456
#=============69级以后秘境可以选择打哪个=============
秘境选择 = 海底秘境
#=============用来保留60级的书和铁=============
书铁仓库 = 仓库3
自动卖物 = 精铁,制造书,阵法书
#=============宝石自动存仓，没在列表里的宝石会自动卖掉=============
宝石仓库 = 免费仓库1
保留宝石 = 太阳石,舍利子,翡翠石,月亮石,昆仑玉,神秘石,红纹石,黑宝石, 玄武石,朱雀石,青龙石,白虎石,仙气,星辰碎片
自动上架 = 佛跳墙,臭豆腐,桂花丸,珍露酒,长寿面,蛇胆酒,五龙丹,九转回魂丹,金香玉,定神香
#=============老区不用保留这几个=============
不自动上架 = 水晶帽,风月宝链,追星踏月
#=============自动使用药品、消耗品和丢垃圾=============
丢垃圾 = True
垃圾 = 上古灵符,上古护符,上古咒符,红罗羹,绿芦羹,九转金丹,修炼丹
#=============东海封妖副本中奶妈加血，其余防御=============
奶妈 = 2
#=============任务相关设置=============
捉鬼次数 = 6
东海封妖 = True
自动侠义 = False
自动领双 = True
#=============活力的消耗方式=============
自动烹饪 = False
自动炼药 = True
#=============师门任务第7次以前如果要这里的物品直接放弃任务=============
师门贵重物品 = 蛇胆酒,青钢刺,佛跳墙,臭豆腐,桂花丸,珍露酒,长寿面,蛇胆酒,金香玉,定神香
#=============帮派任务如果要这里的物品直接放弃任务=============
帮派贵重物品 = 

[OCR配置]
ocr_api = xxx
#=============文字识别大模型精度：高精度、标准、轻量=============
精度 = 标准

[截图]
